---
title: "О работе лаборатории 2023--2025"
institute: "Международная лаборатория языковой конвергенции"
author: "Г. А. Мороз"
date: "12/02/2025"
date-format: "D.MM.YYYY"
format: 
  beamer:
    theme: default
    aspectratio: 169
    mainfont: HSE Sans
    monofont: Iosevka
    df-print: kable
    pdf-engine: xelatex
    cite-method: natbib
    classoption: t
    include-in-header: template.tex
urlcolor: HSEgreen
citecolor: HSEgreen
lang: ru
execute:
  eval: false
  message: false
  warning: false
editor_options: 
  chunk_output_type: console
---

## \alert{\underline{Миссия}} Международной лаборатории языковой конвергенции

\setcounter{framenumber}{1}

- исследование контактных явлений в языках России и диалектах русского языка \pause
- документация
  - малых языков России
  - диалектов русского языка
  - билингвальной речи на русском языке \pause
- разработка и поддержка электронных ресурсов
  - устных корпусов
  - онлайн словарей
  - дигитализация бумажных словарей
  - лингвистических баз данных

## \alert{\underline{Команда}} Международной лаборатории языковой конвергенции

- 2 российских постдока, 1 стажировка

## \alert{\underline{Семинары}} Международной лаборатории языковой конвергенции

## \alert{\underline{Проекты}} Международной лаборатории языковой конвергенции

## \alert{\underline{Экспедиции}} Международной лаборатории языковой конвергенции

## \alert{\underline{Результаты}} Международной лаборатории языковой конвергенции

## \alert{\underline{СМИ о}} Международной лаборатории языковой конвергенции

- регулярно публикуются новости на сайте лаборатории <https://ilcl.hse.ru/>: в 2023 22 сообщения; в 2024 17 сообщений; в 2025 27 сообщений \pause
- новости лаборатории освещаются на портале НИУ ВШЭ, на страницах и в Telegram-каналах Школы Лингвистики и Факультета гуманитарных наук  \pause
- 7 новостей на первой странице портала НИУ ВШЭ  за 2025 год: \tiny
  - [«Пока на языке говорит молодежь, живет надежда на его будущее»](https://www.hse.ru/news/science/1045320540.html)
  - [«Двадцать против десяти: в НИУ ВШЭ проанализировали, как развивались числительные у лезгинских народов»](https://www.hse.ru/news/science/1045320540.html)
  - [«Лингвисты НИУ ВШЭ выяснили, как билингвы используют конструкции с числительными в русском языке»](https://www.hse.ru/news/science/1050582618.html)
  - [«Нет цели сказать, как правильно. Мы стремимся исследовать вариативность»](https://www.hse.ru/news/science/1060826945.html)
  - [«Мы описываем бесписьменные языки»](https://www.hse.ru/news/science/1068423445.html)
  - [Аспирантку НИУ ВШЭ наградили за лучший доклад на 58-й конференции Societas Linguistica Europaea](https://www.hse.ru/news/science/1082849379.html)
  - [«Наша задача — распространять и популяризировать родные языки»](https://www.hse.ru/news/science/1096812524.html)

## \alert{\underline{Проблемы}} Международной лаборатории языковой конвергенции

- кадровый голод
  - сильные ученые, оставшиеся в России, задействованы во множестве проектов
  - к нам не подаются иностранные постдоки
  - в прошлом году к нам не подались даже российские постдоки \pause
- проблемы с публикациями
  - большинство славистических журналов из списка А снимают аффилиацию
  - достаточно большая неопределенность возникает с публикациями Online First
    - Одна из наших статей в Studies in Language:
    - Received: 17 октября 2023
    - Accepted: 08 февраля 2024
    - Online First: 27 августа 2024
    - Published: 10 октября 2025 \pause
- встраивание в объединенный проект (ФИ-2025-32)
  - дополнительная бюрократическая нагрузка
  - в дополнение к требованиям НИУ ВШЭ добавляются требования РАН
    - в борьбе с мелкими темами мы вынуждены переформатировать уже активные проекты
